name: publish-code-on-github-pages
run-name: ${{ github.actor }} is publishing code on GitHub Pages
on:
  push:
    branches: [add-ci-cd]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build

  archive-build-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: public/static/
